//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSA.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000")]
        public string DataCenterRootUrl {
            get {
                return ((string)(this["DataCenterRootUrl"]));
            }
            set {
                this["DataCenterRootUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/data/get-last-datetime")]
        public string LastDatetimeUrl {
            get {
                return ((string)(this["LastDatetimeUrl"]));
            }
            set {
                this["LastDatetimeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/data/add")]
        public string DataUrl {
            get {
                return ((string)(this["DataUrl"]));
            }
            set {
                this["DataUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=sandbox;Integrated Security=true")]
        public string AnalyticsConnectionString {
            get {
                return ((string)(this["AnalyticsConnectionString"]));
            }
            set {
                this["AnalyticsConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Agency {
            get {
                return ((string)(this["Agency"]));
            }
            set {
                this["Agency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gJBJj5UIS1MEyNbExQj6o8fzLBYy6MHM")]
        public string ApiKey {
            get {
                return ((string)(this["ApiKey"]));
            }
            set {
                this["ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nuVhBSBwLqSHQHIEJAQubZQ0OvDmTTZwDk7TttViJ9O6xzCZtuaeGWExgXOwO1NN")]
        public string ApiKeySecret {
            get {
                return ((string)(this["ApiKeySecret"]));
            }
            set {
                this["ApiKeySecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/keys/test")]
        public string TestUrl {
            get {
                return ((string)(this["TestUrl"]));
            }
            set {
                this["TestUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RunInterval {
            get {
                return ((int)(this["RunInterval"]));
            }
            set {
                this["RunInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intterra Data Shipping App")]
        public string TaskName {
            get {
                return ((string)(this["TaskName"]));
            }
            set {
                this["TaskName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reads incident response data from RMS data sources as configured and send to Intt" +
            "erra\'s secure API")]
        public string TaskDescription {
            get {
                return ((string)(this["TaskDescription"]));
            }
            set {
                this["TaskDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string AnalyticsIncidentsSelect {
            get {
                return ((string)(this["AnalyticsIncidentsSelect"]));
            }
            set {
                this["AnalyticsIncidentsSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.incident_summary")]
        public string AnalyticsIncidentsFrom {
            get {
                return ((string)(this["AnalyticsIncidentsFrom"]));
            }
            set {
                this["AnalyticsIncidentsFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("last_updated_rms > \'{{LASTUPDATEDDATETIME}}\'")]
        public string AnalyticsIncidentsWhere {
            get {
                return ((string)(this["AnalyticsIncidentsWhere"]));
            }
            set {
                this["AnalyticsIncidentsWhere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("incident_datetime")]
        public string AnalyticsIncidentsOrderBy {
            get {
                return ((string)(this["AnalyticsIncidentsOrderBy"]));
            }
            set {
                this["AnalyticsIncidentsOrderBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string AnalyticsUnitsSelect {
            get {
                return ((string)(this["AnalyticsUnitsSelect"]));
            }
            set {
                this["AnalyticsUnitsSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.unit_summary")]
        public string AnalyticsUnitsFrom {
            get {
                return ((string)(this["AnalyticsUnitsFrom"]));
            }
            set {
                this["AnalyticsUnitsFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("last_updated_rms > \'{{LASTUPDATEDDATETIME}}\'")]
        public string AnalyticsUnitsWhere {
            get {
                return ((string)(this["AnalyticsUnitsWhere"]));
            }
            set {
                this["AnalyticsUnitsWhere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("last_updated_rms")]
        public string AnalyticsUnitsOrderBy {
            get {
                return ((string)(this["AnalyticsUnitsOrderBy"]));
            }
            set {
                this["AnalyticsUnitsOrderBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Limit {
            get {
                return ((int)(this["Limit"]));
            }
            set {
                this["Limit"] = value;
            }
        }
    }
}
